3th PR - Room implementation
AndresConfortiGL/MarvelApp pull request #4
Opened 2022-09-21 18:23 UTC by AndresConfortiGL

## Description
3th PR - Room was implemented to the project.

## Story Type
- New feature :white_check_mark:
- Change request
- Bug fix
- Tech

## How Can This Be Tested?
By running the app, you will be able to press the button and get prompted by a loading icon, then the data is fetched and saved on the database.

## Evidences
| Pixel 3a | Nexus S |
| ------------- | ------------- |
|![pixel](https://user-images.githubusercontent.com/109096226/190240064-81936a03-0715-4323-b94d-1f10357a4ea4.gif)|![nexus](https://user-images.githubusercontent.com/109096226/190239140-6e4ec0d1-f3f5-4ec3-9b41-b0d6aed9ad40.gif)|

| Coverage Test  |
| ------------- |
|IN PROCCESS|

## Checklist
- All unit Test passed 🚫

## Tested on
The project was tested on Android 8.0 / API 26 using the following devices:

- Pixel 3a
- Nexus S

## Package Structure
| Structure |
| ------------- |
|![image](https://user-images.githubusercontent.com/109096226/191580698-217cdaea-5c15-46e1-be9a-00f48c53bc8a.png)|

2022-09-21 19:40 UTC, SartiMau approved these changes

2022-09-22 17:18 UTC, kearneyeduardo approved these changes

2022-09-22 19:35 UTC, SartiMau requested changes

2022-09-22 19:35 UTC, SartiMau commented on app/src/main/java/com/example/marvelapp/database/MarvelDBImpl.kt
> +    abstract fun charactersDao(): MarvelDao
what is this for?

2022-09-22 21:13 UTC, AndresConfortiGL commented on app/src/main/java/com/example/marvelapp/database/MarvelDBImpl.kt
> +    abstract fun charactersDao(): MarvelDao
Solved in a meet.

2022-09-22 21:25 UTC, SartiMau approved these changes

2022-09-23 20:39 UTC, DiegoDiazGlobant approved these changes

2022-09-26 16:07 UTC, merged